version: '3'
services:
  database:
    container_name: database
    image: mysql:5.7
    command: [ "--default-authentication-plugin=mysql_native_password" ]
    environment:
      - MYSQL_DATABASE=students_grades_api
      - MYSQL_USER=students_grades_api_user
      - MYSQL_PASSWORD=students_grades_api_password
      - MYSQL_ROOT_PASSWORD=students_grades_api_password
    ports:
      - "3306:3306"
    volumes:
      - ./database/data:/var/lib/mysql

  php-fpm:
    container_name: php-fpm
    build: ./php-fpm
    expose:
      - "9000"
    volumes:
      - ./../../../:/var/www/app:cached
    depends_on:
      - database
    links:
      - database

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "8080:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    volumes:
      - ./../../../:/var/www/app:cached
    depends_on:
      - database
    links:
      - php-fpm
