parameters:
    openapi_specifications_file_path: '%kernel.project_dir%/config/statics/openapi_specifications.yaml'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    StudentsGradesApi\:
        resource: '../src/'
        exclude:
            - '../src/Domain/Model'
            - '../src/Domain/ValueObject'
            - '../src/Infrastructure/HttpApi/Symfony/Kernel.php'

    StudentsGradesApi\Infrastructure\HttpApi\Symfony\Controller\:
        resource: '../src/Infrastructure/HttpApi/Symfony/Controller/'
        tags: ['controller.service_arguments']
